/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiAdminsSignUpApplicationsParams,
  GetPendingApplicationsResponse,
  ProblemDetails
} from '../../models';





export type postApiAdminsSignUpApplicationsApplicationIdApproveResponse204 = {
  data: void
  status: 204
}

export type postApiAdminsSignUpApplicationsApplicationIdApproveResponse404 = {
  data: ProblemDetails
  status: 404
}

export type postApiAdminsSignUpApplicationsApplicationIdApproveResponse500 = {
  data: ProblemDetails
  status: 500
}

export type postApiAdminsSignUpApplicationsApplicationIdApproveResponseSuccess = (postApiAdminsSignUpApplicationsApplicationIdApproveResponse204) & {
  headers: Headers;
};
export type postApiAdminsSignUpApplicationsApplicationIdApproveResponseError = (postApiAdminsSignUpApplicationsApplicationIdApproveResponse404 | postApiAdminsSignUpApplicationsApplicationIdApproveResponse500) & {
  headers: Headers;
};

export type postApiAdminsSignUpApplicationsApplicationIdApproveResponse = (postApiAdminsSignUpApplicationsApplicationIdApproveResponseSuccess | postApiAdminsSignUpApplicationsApplicationIdApproveResponseError)

export const getPostApiAdminsSignUpApplicationsApplicationIdApproveUrl = (applicationId: number,) => {


  

  return `/api/admins/sign-up-applications/${applicationId}/approve`
}

export const postApiAdminsSignUpApplicationsApplicationIdApprove = async (applicationId: number, options?: RequestInit): Promise<postApiAdminsSignUpApplicationsApplicationIdApproveResponse> => {
  
  const res = await fetch(getPostApiAdminsSignUpApplicationsApplicationIdApproveUrl(applicationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAdminsSignUpApplicationsApplicationIdApproveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAdminsSignUpApplicationsApplicationIdApproveResponse
}
  



export const getPostApiAdminsSignUpApplicationsApplicationIdApproveMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>, TError,{applicationId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>, TError,{applicationId: number}, TContext> => {

const mutationKey = ['postApiAdminsSignUpApplicationsApplicationIdApprove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>, {applicationId: number}> = (props) => {
          const {applicationId} = props ?? {};

          return  postApiAdminsSignUpApplicationsApplicationIdApprove(applicationId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminsSignUpApplicationsApplicationIdApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>>
    
    export type PostApiAdminsSignUpApplicationsApplicationIdApproveMutationError = ProblemDetails

    export const usePostApiAdminsSignUpApplicationsApplicationIdApprove = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>, TError,{applicationId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdApprove>>,
        TError,
        {applicationId: number},
        TContext
      > => {
      return useMutation(getPostApiAdminsSignUpApplicationsApplicationIdApproveMutationOptions(options), queryClient);
    }
    export type getApiAdminsSignUpApplicationsResponse200 = {
  data: GetPendingApplicationsResponse
  status: 200
}

export type getApiAdminsSignUpApplicationsResponseSuccess = (getApiAdminsSignUpApplicationsResponse200) & {
  headers: Headers;
};
;

export type getApiAdminsSignUpApplicationsResponse = (getApiAdminsSignUpApplicationsResponseSuccess)

export const getGetApiAdminsSignUpApplicationsUrl = (params: GetApiAdminsSignUpApplicationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admins/sign-up-applications?${stringifiedParams}` : `/api/admins/sign-up-applications`
}

export const getApiAdminsSignUpApplications = async (params: GetApiAdminsSignUpApplicationsParams, options?: RequestInit): Promise<getApiAdminsSignUpApplicationsResponse> => {
  
  const res = await fetch(getGetApiAdminsSignUpApplicationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAdminsSignUpApplicationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAdminsSignUpApplicationsResponse
}
  




export const getGetApiAdminsSignUpApplicationsQueryKey = (params?: GetApiAdminsSignUpApplicationsParams,) => {
    return [
    `/api/admins/sign-up-applications`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetApiAdminsSignUpApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError = unknown>(params: GetApiAdminsSignUpApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminsSignUpApplicationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>> = ({ signal }) => getApiAdminsSignUpApplications(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminsSignUpApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>>
export type GetApiAdminsSignUpApplicationsQueryError = unknown


export function useGetApiAdminsSignUpApplications<TData = Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError = unknown>(
 params: GetApiAdminsSignUpApplicationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminsSignUpApplications<TData = Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError = unknown>(
 params: GetApiAdminsSignUpApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminsSignUpApplications<TData = Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError = unknown>(
 params: GetApiAdminsSignUpApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAdminsSignUpApplications<TData = Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError = unknown>(
 params: GetApiAdminsSignUpApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminsSignUpApplications>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminsSignUpApplicationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type postApiAdminsSignUpApplicationsApplicationIdRejectResponse204 = {
  data: void
  status: 204
}

export type postApiAdminsSignUpApplicationsApplicationIdRejectResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postApiAdminsSignUpApplicationsApplicationIdRejectResponse404 = {
  data: ProblemDetails
  status: 404
}

export type postApiAdminsSignUpApplicationsApplicationIdRejectResponseSuccess = (postApiAdminsSignUpApplicationsApplicationIdRejectResponse204) & {
  headers: Headers;
};
export type postApiAdminsSignUpApplicationsApplicationIdRejectResponseError = (postApiAdminsSignUpApplicationsApplicationIdRejectResponse400 | postApiAdminsSignUpApplicationsApplicationIdRejectResponse404) & {
  headers: Headers;
};

export type postApiAdminsSignUpApplicationsApplicationIdRejectResponse = (postApiAdminsSignUpApplicationsApplicationIdRejectResponseSuccess | postApiAdminsSignUpApplicationsApplicationIdRejectResponseError)

export const getPostApiAdminsSignUpApplicationsApplicationIdRejectUrl = (applicationId: number,) => {


  

  return `/api/admins/sign-up-applications/${applicationId}/reject`
}

export const postApiAdminsSignUpApplicationsApplicationIdReject = async (applicationId: number, options?: RequestInit): Promise<postApiAdminsSignUpApplicationsApplicationIdRejectResponse> => {
  
  const res = await fetch(getPostApiAdminsSignUpApplicationsApplicationIdRejectUrl(applicationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAdminsSignUpApplicationsApplicationIdRejectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAdminsSignUpApplicationsApplicationIdRejectResponse
}
  



export const getPostApiAdminsSignUpApplicationsApplicationIdRejectMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>, TError,{applicationId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>, TError,{applicationId: number}, TContext> => {

const mutationKey = ['postApiAdminsSignUpApplicationsApplicationIdReject'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>, {applicationId: number}> = (props) => {
          const {applicationId} = props ?? {};

          return  postApiAdminsSignUpApplicationsApplicationIdReject(applicationId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminsSignUpApplicationsApplicationIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>>
    
    export type PostApiAdminsSignUpApplicationsApplicationIdRejectMutationError = ProblemDetails

    export const usePostApiAdminsSignUpApplicationsApplicationIdReject = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>, TError,{applicationId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminsSignUpApplicationsApplicationIdReject>>,
        TError,
        {applicationId: number},
        TContext
      > => {
      return useMutation(getPostApiAdminsSignUpApplicationsApplicationIdRejectMutationOptions(options), queryClient);
    }
    