/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LogInRequest,
  ProblemDetails,
  SignUpRequest
} from '../../models';





export type postApiUsersLoginResponse200 = {
  data: string
  status: 200
}

export type postApiUsersLoginResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postApiUsersLoginResponseSuccess = (postApiUsersLoginResponse200) & {
  headers: Headers;
};
export type postApiUsersLoginResponseError = (postApiUsersLoginResponse400) & {
  headers: Headers;
};

export type postApiUsersLoginResponse = (postApiUsersLoginResponseSuccess | postApiUsersLoginResponseError)

export const getPostApiUsersLoginUrl = () => {


  

  return `/api/users/login`
}

export const postApiUsersLogin = async (logInRequest: LogInRequest, options?: RequestInit): Promise<postApiUsersLoginResponse> => {
  
  const res = await fetch(getPostApiUsersLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logInRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiUsersLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiUsersLoginResponse
}
  



export const getPostApiUsersLoginMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersLogin>>, TError,{data: LogInRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersLogin>>, TError,{data: LogInRequest}, TContext> => {

const mutationKey = ['postApiUsersLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersLogin>>, {data: LogInRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsersLogin(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersLogin>>>
    export type PostApiUsersLoginMutationBody = LogInRequest
    export type PostApiUsersLoginMutationError = ProblemDetails

    export const usePostApiUsersLogin = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersLogin>>, TError,{data: LogInRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersLogin>>,
        TError,
        {data: LogInRequest},
        TContext
      > => {
      return useMutation(getPostApiUsersLoginMutationOptions(options), queryClient);
    }
    export type postApiUsersSignupResponse204 = {
  data: void
  status: 204
}

export type postApiUsersSignupResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postApiUsersSignupResponse409 = {
  data: ProblemDetails
  status: 409
}

export type postApiUsersSignupResponseSuccess = (postApiUsersSignupResponse204) & {
  headers: Headers;
};
export type postApiUsersSignupResponseError = (postApiUsersSignupResponse400 | postApiUsersSignupResponse409) & {
  headers: Headers;
};

export type postApiUsersSignupResponse = (postApiUsersSignupResponseSuccess | postApiUsersSignupResponseError)

export const getPostApiUsersSignupUrl = () => {


  

  return `/api/users/signup`
}

export const postApiUsersSignup = async (signUpRequest: SignUpRequest, options?: RequestInit): Promise<postApiUsersSignupResponse> => {
  
  const res = await fetch(getPostApiUsersSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signUpRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiUsersSignupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiUsersSignupResponse
}
  



export const getPostApiUsersSignupMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSignup>>, TError,{data: SignUpRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSignup>>, TError,{data: SignUpRequest}, TContext> => {

const mutationKey = ['postApiUsersSignup'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersSignup>>, {data: SignUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsersSignup(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersSignupMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersSignup>>>
    export type PostApiUsersSignupMutationBody = SignUpRequest
    export type PostApiUsersSignupMutationError = ProblemDetails

    export const usePostApiUsersSignup = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersSignup>>, TError,{data: SignUpRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersSignup>>,
        TError,
        {data: SignUpRequest},
        TContext
      > => {
      return useMutation(getPostApiUsersSignupMutationOptions(options), queryClient);
    }
    