/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */
import type { SignUpApplication } from './signUpApplication';

export interface GetPendingApplicationsResponse {
  /** @nullable */
  applications?: SignUpApplication[] | null;
  currentPage?: number;
  totalPages?: number;
}
