/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */

export interface LogInRequest {
  /** @nullable */
  login?: string | null;
  /** @nullable */
  password?: string | null;
}
