/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}
