/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */

export type SignUpApplicationStatus = typeof SignUpApplicationStatus[keyof typeof SignUpApplicationStatus];


export const SignUpApplicationStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
