/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */
import type { SignUpApplicationStatus } from './signUpApplicationStatus';
import type { UserType } from './userType';

export interface SignUpApplication {
  id?: number;
  readonly createdAtUtc?: string;
  /** @nullable */
  readonly fullName?: string | null;
  type?: UserType;
  /** @nullable */
  readonly group?: string | null;
  /** @nullable */
  readonly login?: string | null;
  /** @nullable */
  readonly passwordHash?: string | null;
  status?: SignUpApplicationStatus;
}
