/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */

export interface SignUpRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  userType?: string | null;
  /** @nullable */
  group?: string | null;
  /** @nullable */
  login?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  confirmPassword?: string | null;
}
