/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * EduGraph.Core
 * OpenAPI spec version: 1.0
 */

export type UserType = typeof UserType[keyof typeof UserType];


export const UserType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
