<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

        <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
        <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
        <OpenApiGenerateDocumentsOptions>--file-name openapi</OpenApiGenerateDocumentsOptions>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="FluentValidation" Version="12.1.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="9.0.15">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.15" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.2" />
        <PackageReference Include="Scrutor" Version="7.0.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\aspire\EduGraph.ServiceDefaults\EduGraph.ServiceDefaults.csproj" />
      <ProjectReference Include="..\EduGraph.Infrastructure.GoogleDrive\EduGraph.Infrastructure.GoogleDrive.csproj" />
      <ProjectReference Include="..\EduGraph.Infrastructure.VectorSearch\EduGraph.Infrastructure.VectorSearch.csproj" />
      <ProjectReference Include="..\EduGraph.Infrastructure.SQLite\EduGraph.Infrastructure.SQLite.csproj" />
      <ProjectReference Include="..\EduGraph.SharedKernel\EduGraph.SharedKernel.csproj" />
    </ItemGroup>

</Project>
