<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
      <PackageReference Include="Google.Apis.Drive.v3" Version="1.72.0.3970" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.11" />
      <PackageReference Include="PdfPig" Version="0.1.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EduGraph.SharedKernel\EduGraph.SharedKernel.csproj" />
    </ItemGroup>

</Project>
